swagger: '2.0'
info:
  title: api 文档
  description: api 文档描述
  version: '1.0.0'
host: api.domain.com
schemes:
  - http
produces:
  - application/json

tags:
  - name: users
    description: 用户相关 API

paths:
  /users:
    $ref: './paths/users/index.yaml'
  /users/{uuid}:
    $ref: './paths/users/by-uuid.yaml'
